apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bookmark-app
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/bookmark-app:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
        env:
        - name: INSTANCE_CONNECTION_NAME
          value: "PROJECT_ID:REGION:INSTANCE_NAME"
        - name: DB_USER
          value: "dbuser"
        - name: DB_NAME
          value: "bookmarkdb"
