#!/bin/bash

# Cloud Run デプロイ設定情報表示スクリプト

PROJECT_ID="bookmark-app-1748244130"
REGION="asia-northeast1"
SERVICE_NAME="bookmark-app"
INSTANCE_CONNECTION_NAME="${PROJECT_ID}:${REGION}:bookmark-db"

echo "=================================="
echo "🚀 GCP Cloud Run デプロイ設定完了"
echo "=================================="
echo ""
echo "📋 プロジェクト情報:"
echo "  プロジェクトID: $PROJECT_ID"
echo "  リージョン: $REGION"
echo "  サービス名: $SERVICE_NAME"
echo ""
echo "🔐 GitHub Secrets 設定値 (設定済み):"
echo "-----------------------------------"
echo "PROJECT_ID: $PROJECT_ID"
echo "SERVICE_NAME: $SERVICE_NAME"
echo "REGION: $REGION"
echo "INSTANCE_CONNECTION_NAME: $INSTANCE_CONNECTION_NAME"
echo "DB_USER: dbuser"
echo "DB_PASS: BookmarkApp123!"
echo "DB_NAME: bookmarkdb"
echo "SECRET_KEY: [ランダム文字列を設定]"
echo ""
echo "📊 Cloud SQL インスタンス状況:"
echo "-----------------------------------"
gcloud sql instances list --filter="name:bookmark-db" --format="table(name,state,databaseVersion,region)"
echo ""
echo "🔧 次のステップ:"
echo "1. Cloud SQLインスタンスの作成完了を待つ"
echo "2. データベースとユーザーを作成"
echo "3. mainブランチにプッシュしてデプロイテスト"